---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - VERSION=docker
    volumes:
      - /mnt/plex/config:/config
      - /mnt/plex/tv:/tv
      - /mnt/plex/movies:/movies
      - /mnt/plex/documentary:/documentary
      - /mnt/plex/anime:/anime
    restart: unless-stopped
